spring.datasource.url=jdbc:postgresql://dpg-d948pc28qa3s73c47st0-a.oregon-postgres.render.com:5432/sicjacdb
spring.datasource.username=sicjacdb_user
spring.datasource.password=d2sZn1uMmBMBgZ2EhMDevoTj9NHLkGyx
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html
server.port=8081